version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: go-server
        ports:
            - "8080:8080"
        env_file:
            - .env
        depends_on:
            postgres:
                condition: service_healthy
            test-postgres:
                condition: service_healthy

    # Основная БД
    postgres:
        image: postgres:16
        container_name: pr-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pr_db
        ports:
            - "5433:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Тестовая БД
    test-postgres:
        image: postgres:16
        container_name: pr-test-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: pr_db_test
        ports:
            - "5434:5432"
        volumes:
            - test_postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

    # Мигратор для основной базы
    migrator:
        image: migrate/migrate:latest
        container_name: pr-migrator
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - ./migrations:/migrations
        entrypoint: [
            "migrate",
            "-path", "/migrations",
            "-database", "postgres://postgres:postgres@postgres:5432/pr_db?sslmode=disable",
            "up"
        ]
        restart: "on-failure"

    # Мигратор для тестовой базы
    test-migrator:
        image: migrate/migrate:latest
        container_name: pr-test-migrator
        depends_on:
            test-postgres:
                condition: service_healthy
        volumes:
            - ./migrations:/migrations
        entrypoint: [
            "migrate",
            "-path", "/migrations",
            "-database", "postgres://postgres:postgres@test-postgres:5432/pr_db_test?sslmode=disable",
            "up"
        ]
        restart: "on-failure"

volumes:
    postgres_data:
    test_postgres_data:
